WebStore/WebStore/Models/SessionCart.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using WebStore.Helpers;

namespace WebStore.Models
{
    public class SessionCart : Cart
    {
        public static Cart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?
                .HttpContext.Session;
            SessionCart cart = session?.GetJson<SessionCart>("Cart")
                               ?? new SessionCart();
            cart.Session = session;
            return cart;
        }

        [JsonIgnore]
        public ISession Session { get; set; }

        public override void AddItem(Product product, int quantity)
        {
            base.AddItem(product, quantity);
            Session.SetJson("Cart", this);
        }

        public override void RemoveLine(Product product)
        {
            base.RemoveLine(product);
            Session.SetJson("Cart", this);
        }

        public override void Clear()
        {
            base.Clear();
            Session.Remove("Cart");
        }
    }
}

WebStore/WebStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Models;

namespace WebStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private  readonly Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

WebStore/WebStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.Contracts;
using WebStore.Models;

namespace WebStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IProductManager _productManager;

        public NavigationMenuViewComponent(IProductManager productManager)
        {
            _productManager = productManager;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_productManager.Get().Select(x=>x.Category).Distinct().OrderBy(x=>x).ToList());
        }
    }
}

WebStore/WebStore/Controllers/CartController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Contracts;
using WebStore.Models;
using WebStore.Models.ViewModels;

namespace WebStore.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductManager _productManager;
        private readonly Cart _cart;

        public CartController(IProductManager productManager, Cart cartService)
        {
            _productManager = productManager;
            _cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = _cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(Guid id, string returnUrl)
        {
            Product product = _productManager.Get()
                .FirstOrDefault(p => p.Id == id);

            if (product != null)
            {
                _cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(Guid productId,
            string returnUrl)
        {
            Product product = _productManager.Get()
                .FirstOrDefault(p => p.Id == productId);

            if (product != null)
            {
                _cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

WebStore/WebStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Contracts;
using WebStore.Models.ViewModels;

namespace WebStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductManager _productManager;

        public int PageSize = 2;

        public ProductController(IProductManager productManager)
        {
            _productManager = productManager;
        }

        public ViewResult List(string category,int pageNumber)
        {
            var products = _productManager.Get();

            return View(new ProductListViewModel
            {
                Products = products.Where(x=> category == null || x.Category == category).Skip((pageNumber - 1) * PageSize).Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = pageNumber,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? products.Count : products.Count(x => x.Category == category)
                },
                CurrentCategory = category
            });
        }

    }
}

WebStore/WebStore/Views/Cart/Index.cshtml
@model CartIndexViewModel

<h2>Your cart</h2>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th class="text-right">Price</th>
        <th class="text-right">Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.Cart.Lines) {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.Price).ToString("c"))
            </td>
            <td>
                <form asp-action="RemoveFromCart" method="post">
                    <input type="hidden" name="ProductID"
                           value="@line.Product.Id" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total:</td>
        <td class="text-right">
            @Model.Cart.ComputeTotalValue().ToString("c")
        </td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
</div>

WebStore/WebStore/Views/Product/List.cshtml
@model ProductListViewModel

@foreach (var product in Model.Products)
{
    @Html.Partial("ProductSummary", product);

}

<div page-model="@Model.PagingInfo" page-action="List" page-classes-enabled="true"
     page-class="btn" page-class-normal="btn-secondary"
     page-class-selected="btn-primary" 
     page-url-category="@Model.CurrentCategory"
     class="btn-group pull-right m-1">
</div>

WebStore/WebStore/Views/Shared/Components/CartSummary/Default.cshtml
@using WebStore.Helpers
@model Cart

<div class="">
    @if (Model.Lines.Any())
    {
        <small class="navbar-text">
            <b>Your cart:</b>
            @Model.Lines.Sum(x => x.Quantity) item(s)
            @Model.ComputeTotalValue().ToString("c")
        </small>
    }
    <a class="btn btn-sm btn-secondary navbar-btn"
       asp-controller="Cart" asp-action="Index"
       asp-route-returnurl="@ViewContext.HttpContext.Request.PathAndQuery()">
        <i class="fa fa-shopping-cart"></i>
    </a>
</div>

WebStore/WebStore/Views/Shared/Components/NavigationMenu/Default.cshtml
@model List<string>

<a class="btn btn-block btn-secondary"
   asp-action="List"
   asp-controller="Product"
   asp-route-category="">
    Home
</a>

@foreach (string category in Model)
{
    <a class="btn btn-block
       @(category == ViewBag.SelectedCategory ? "btn-primary": "btn-secondary")"
       asp-action="List"
       asp-controller="Product"
       asp-route-category="@category"
       asp-route-pageNumber="1">
        @category
    </a>
}

WebStore/WebStore/Views/Shared/ProductSummary.cshtml
@using WebStore.Helpers
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.Id" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

WebStore/WebStore/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <title>Web Store</title>
</head>
<body>
    <div>
        <div class="navbar navbar-inverse bg-inverse" role="navigation">
            <div class="row">
                <a class="col navbar-brand" href="#">SPORTS STORE</a>
                <div class="col-4 text-right">
                    @await Component.InvokeAsync("CartSummary")
                </div>
            </div>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="/node_modules/jquery/dist/jquery.js"></script>
    <script src="/node_modules/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>